import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import MainPage from "../components/MainPage";
import Sample from "../components/sample";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MainPage />
        <Sample />
      </main>
    </div>
  );
};

export default Home;
